config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-acc-library:
      branch: main
      repo: https://github.com/ARGOeu/argo-acc-library
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-acc-library git:
        commands:
        - /usr/bin/env sh .sqa/script.grege_bubbly_penguin.sh
        container: qc.acc_cinnamon_cheerful_macaw
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-acc-library find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gray_amused_jaguar.sh
        container: qc.doc_brown_friendly_tortoise
      github.com/ARGOeu/argo-acc-library git:
        commands:
        - /usr/bin/env sh .sqa/script.tide_tactful_frog.sh
        container: qc.doc_polar_frugal_ostrich
      github.com/ARGOeu/argo-acc-library markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.claret_bright_panther.sh
        container: qc.doc_currant_kind_capybara
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-acc-library licensee:
        commands:
        - /usr/bin/env sh .sqa/script.forest_kind_seahorse.sh
        container: qc.lic_verdant_kind_llama
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-acc-library bandit:
        commands:
        - /usr/bin/env sh .sqa/script.espresso_passionate_nymph.sh
        container: qc.sec_puce_perceptive_tiger
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-acc-library flake8:
        commands:
        - /usr/bin/env sh .sqa/script.purple_analytical_kraken.sh
        container: qc.sty_gold_delighted_condor
  QC.Uni:
    repos:
      github.com/ARGOeu/argo-acc-library pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sepia_audacious_boar.sh
        container: qc.uni_glaucous_empathetic_giraffe
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-acc-library get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.heather_intuitive_toad.sh
        container: qc.ver_umber_timid_spren
timeout: 5400
